# Generated by Django 5.2.1 on 2025-05-26 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('description', models.TextField(verbose_name='Description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='bouquets/', verbose_name='Photo')),
                ('tag', models.CharField(max_length=100, verbose_name='Tag')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Bouquet',
                'verbose_name_plural': 'Bouquets',
            },
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('description', models.TextField(verbose_name='Description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='flowers/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Flower',
                'verbose_name_plural': 'Flowers',
            },
        ),
        migrations.CreateModel(
            name='Ribbon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('description', models.TextField(verbose_name='Description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='ribbons/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Ribbon',
                'verbose_name_plural': 'Ribbons',
            },
        ),
        migrations.CreateModel(
            name='Wrapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('description', models.TextField(verbose_name='Description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='wrappers/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Wrapper',
                'verbose_name_plural': 'Wrappers',
            },
        ),
        migrations.CreateModel(
            name='BouquetFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flower_items', to='catalog.bouquet')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouquet_items', to='catalog.flower')),
            ],
            options={
                'verbose_name': 'Bouquet Flower',
                'verbose_name_plural': 'Bouquet Flowers',
            },
        ),
        migrations.AddField(
            model_name='bouquet',
            name='flowers',
            field=models.ManyToManyField(related_name='bouquets', through='catalog.BouquetFlower', to='catalog.flower'),
        ),
        migrations.CreateModel(
            name='BouquetRibbon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(verbose_name='Length')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ribbon_items', to='catalog.bouquet')),
                ('ribbon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouquet_items', to='catalog.ribbon')),
            ],
            options={
                'verbose_name': 'Bouquet Ribbon',
                'verbose_name_plural': 'Bouquet Ribbons',
            },
        ),
        migrations.AddField(
            model_name='bouquet',
            name='ribbons',
            field=models.ManyToManyField(related_name='bouquets', through='catalog.BouquetRibbon', to='catalog.ribbon'),
        ),
        migrations.CreateModel(
            name='StockFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(verbose_name='Delivery Date')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('number', models.CharField(max_length=50, verbose_name='Batch Number')),
                ('status', models.CharField(choices=[('available', 'Available'), ('is_used', 'Used'), ('reserved', 'Reserved'), ('damaged', 'Damaged'), ('expired', 'Expired')], default='available', max_length=30, verbose_name='Stock Item Status')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='catalog.flower')),
            ],
            options={
                'verbose_name': 'Stock Flower',
                'verbose_name_plural': 'Stock Flowers',
            },
        ),
        migrations.CreateModel(
            name='StockRibbon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(verbose_name='Delivery Date')),
                ('length', models.PositiveIntegerField(verbose_name='Length')),
                ('status', models.CharField(choices=[('available', 'Available'), ('out_of_stock', 'Out of Stock')], default='available', max_length=30, verbose_name='Stock Item Status')),
                ('ribbon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='catalog.ribbon')),
            ],
            options={
                'verbose_name': 'Stock Ribbon',
                'verbose_name_plural': 'Stock Ribbons',
            },
        ),
        migrations.CreateModel(
            name='StockWrapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(verbose_name='Delivery Date')),
                ('length', models.PositiveIntegerField(verbose_name='Length')),
                ('status', models.CharField(choices=[('available', 'Available'), ('out_of_stock', 'Out of Stock')], default='available', max_length=30, verbose_name='Stock Item Status')),
                ('wrapper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='catalog.wrapper')),
            ],
            options={
                'verbose_name': 'Stock Wrapper',
                'verbose_name_plural': 'Stock Wrappers',
            },
        ),
        migrations.CreateModel(
            name='BouquetWrapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(verbose_name='Length')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrapper_items', to='catalog.bouquet')),
                ('wrapper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouquet_items', to='catalog.wrapper')),
            ],
            options={
                'verbose_name': 'Bouquet Wrapper',
                'verbose_name_plural': 'Bouquet Wrappers',
            },
        ),
        migrations.AddField(
            model_name='bouquet',
            name='wrappers',
            field=models.ManyToManyField(related_name='bouquets', through='catalog.BouquetWrapper', to='catalog.wrapper'),
        ),
    ]
