# Generated by Django 5.2.1 on 2025-05-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockflower",
            options={
                "ordering": ["delivery_date", "id"],
                "verbose_name": "Stock Flower",
                "verbose_name_plural": "Stock Flowers",
            },
        ),
        migrations.AlterModelOptions(
            name="stockribbon",
            options={
                "ordering": ["delivery_date", "id"],
                "verbose_name": "Stock Ribbon",
                "verbose_name_plural": "Stock Ribbons",
            },
        ),
        migrations.AlterModelOptions(
            name="stockwrapper",
            options={
                "ordering": ["delivery_date", "id"],
                "verbose_name": "Stock Wrapper",
                "verbose_name_plural": "Stock Wrappers",
            },
        ),
        migrations.AlterField(
            model_name="stockflower",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("used", "Used"),
                    ("reserved", "Reserved"),
                    ("damaged", "Damaged"),
                    ("expired", "Expired"),
                ],
                default="available",
                max_length=30,
                verbose_name="Stock Item Status",
            ),
        ),
        migrations.AlterField(
            model_name="stockribbon",
            name="length",
            field=models.FloatField(verbose_name="Length"),
        ),
        migrations.AlterField(
            model_name="stockwrapper",
            name="length",
            field=models.FloatField(verbose_name="Length"),
        ),
    ]
