# Generated by Django 5.2.1 on 2025-05-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0002_alter_stockflower_options_alter_stockribbon_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockflower",
            options={
                "verbose_name": "Stock Flower",
                "verbose_name_plural": "Stock Flowers",
            },
        ),
        migrations.AlterModelOptions(
            name="stockribbon",
            options={
                "verbose_name": "Stock Ribbon",
                "verbose_name_plural": "Stock Ribbons",
            },
        ),
        migrations.AlterModelOptions(
            name="stockwrapper",
            options={
                "verbose_name": "Stock Wrapper",
                "verbose_name_plural": "Stock Wrappers",
            },
        ),
        migrations.AlterField(
            model_name="stockflower",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("is_used", "Used"),
                    ("reserved", "Reserved"),
                    ("damaged", "Damaged"),
                    ("expired", "Expired"),
                ],
                default="available",
                max_length=30,
                verbose_name="Stock Item Status",
            ),
        ),
        migrations.AlterField(
            model_name="stockribbon",
            name="length",
            field=models.PositiveIntegerField(verbose_name="Length"),
        ),
        migrations.AlterField(
            model_name="stockwrapper",
            name="length",
            field=models.PositiveIntegerField(verbose_name="Length"),
        ),
    ]
