# Generated by Django 5.2.1 on 2025-05-26 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('ordered', 'Converted to Order'), ('canceled', 'Canceled')], default='active', max_length=30, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.bouquet', verbose_name='Bouquet')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart', verbose_name='Cart')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
            },
        ),
        migrations.CreateModel(
            name='CourierLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'courier'}, on_delete=django.db.models.deletion.CASCADE, related_name='location', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Courier Location',
                'verbose_name_plural': 'Courier Locations',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('paid', 'Оплачен'), ('ready', 'Готов к доставке'), ('delivering', 'Доставляется'), ('delivered', 'Доставлен'), ('completed', 'Выполнен'), ('canceled', 'Отменен')], default='new', max_length=30, verbose_name='Order Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('delivery_datetime', models.DateTimeField(verbose_name='Delivery Date/Time')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Cost')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Delivery Cost')),
                ('delivery_distance', models.FloatField(default=0, verbose_name='Delivery Distance (meters)')),
                ('delivery_address_name', models.CharField(max_length=255, verbose_name='Delivery Address')),
                ('delivery_lat', models.FloatField(verbose_name='Delivery Latitude')),
                ('delivery_lon', models.FloatField(verbose_name='Delivery Longitude')),
                ('courier_lat', models.FloatField(blank=True, null=True, verbose_name='Courier Latitude')),
                ('courier_lon', models.FloatField(blank=True, null=True, verbose_name='Courier Longitude')),
                ('courier_last_update', models.DateTimeField(blank=True, null=True, verbose_name='Courier Location Last Update')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='Recipient Name')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='Recipient Phone')),
                ('cart', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='orders.cart', verbose_name='Cart')),
                ('courier', models.ForeignKey(blank=True, limit_choices_to={'role': 'courier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_orders', to=settings.AUTH_USER_MODEL, verbose_name='Courier')),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
                ('florist', models.ForeignKey(blank=True, limit_choices_to={'role': 'florist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_orders', to=settings.AUTH_USER_MODEL, verbose_name='Florist')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=30, verbose_name='Payment Status')),
                ('payment_method', models.CharField(choices=[('card', 'Card Online'), ('cash', 'Cash on Delivery')], max_length=30, verbose_name='Payment Method')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid at')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy')], default='available', max_length=30, verbose_name='Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Status',
                'verbose_name_plural': 'User Statuses',
            },
        ),
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Shift start date/time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Shift end date/time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_records', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Work Record',
                'verbose_name_plural': 'Work Records',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('price_per_item', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per item')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.bouquet', verbose_name='Bouquet')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'unique_together': {('order', 'bouquet')},
            },
        ),
    ]
